import React from 'react';
import { Shield, ShieldAlert, ShieldCheck, Activity } from 'lucide-react';

const ExecutiveReport = ({ results }) => {
  if (!results) return null;

  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  });

  return (
    
    <div id="executive-pdf-template" style={{ padding: '40px', backgroundColor: '#ffffff', color: '#000000', width: '800px', display: 'none' }}>
          
      {/* --- PAGE 1: Cover Page --- */}
      <div style={{ height: '1020px', display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', textAlign: 'center', borderBottom: '2px solid #e2e8f0' }}>
        <Shield size={80} color="#2563eb" style={{ marginBottom: '20px' }} />
        <h1 style={{ fontSize: '36px', color: '#1e293b', marginBottom: '10px' }}>Executive Security Report</h1>
        <h2 style={{ fontSize: '24px', color: '#64748b', fontWeight: 'normal' }}>Vulnerability & Threat Assessment</h2>
        
        <div style={{ marginTop: '60px', padding: '20px', border: '1px solid #cbd5e1', borderRadius: '8px', backgroundColor: '#f8fafc', width: '80%' }}>
          <p style={{ fontSize: '18px', margin: '5px 0' }}><strong>Target Domain:</strong> {results.domain}</p>
          <p style={{ fontSize: '18px', margin: '5px 0' }}><strong>Date of Scan:</strong> {currentDate}</p>
          <p style={{ fontSize: '18px', margin: '5px 0' }}><strong>Generated By:</strong> SOC Automated System</p>
        </div>
      </div>

      {/* --- PAGE 2: Executive Summary --- */}
      <div style={{ height: '1020px', paddingTop: '40px' }}>
        <h2 style={{ color: '#1e293b', borderBottom: '2px solid #2563eb', paddingBottom: '10px' }}>1. Executive Summary</h2>
        <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#334155' }}>
          This report provides a high-level overview of the security posture for <strong>{results.domain}</strong>. The assessment covers DNS vulnerabilities (SPF, DMARC, DKIM) and external threat intelligence validation.
        </p>

        <div style={{ backgroundColor: '#eff6ff', padding: '20px', borderRadius: '8px', marginTop: '20px', borderLeft: '4px solid #2563eb' }}>
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '10px', color: '#1e3a8a', marginTop: 0 }}>
            <Activity size={20} /> AI Auto-Remediation Plan
          </h3>
          <p style={{ fontSize: '16px', color: '#1e40af', margin: 0, fontWeight: '500' }}>
            {results.ai_remediation}
          </p>
        </div>

        <h2 style={{ color: '#1e293b', borderBottom: '2px solid #2563eb', paddingBottom: '10px', marginTop: '40px' }}>2. Technical Findings</h2>
        <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '20px' }}>
          <thead>
            <tr style={{ backgroundColor: '#1e293b', color: 'white' }}>
              <th style={{ padding: '12px', textAlign: 'left', border: '1px solid #cbd5e1' }}>Security Control</th>
              <th style={{ padding: '12px', textAlign: 'left', border: '1px solid #cbd5e1' }}>Status</th>
              <th style={{ padding: '12px', textAlign: 'left', border: '1px solid #cbd5e1' }}>Details</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', fontWeight: 'bold' }}>SPF Record</td>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', color: results.spf.status === 'Secure' ? 'green' : 'red' }}>{results.spf.status}</td>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', fontSize: '14px' }}>{results.spf.message || 'Record Present'}</td>
            </tr>
            <tr>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', fontWeight: 'bold' }}>DMARC Policy</td>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', color: results.dmarc.status === 'Secure' ? 'green' : 'red' }}>{results.dmarc.status}</td>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', fontSize: '14px' }}>{results.dmarc.message || 'Policy Enforced'}</td>
            </tr>
            <tr>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', fontWeight: 'bold' }}>Threat Intelligence</td>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', color: results.virustotal.status === 'Secure' ? 'green' : 'red' }}>{results.virustotal.status}</td>
              <td style={{ padding: '12px', border: '1px solid #cbd5e1', fontSize: '14px' }}>{results.virustotal.message}</td>
            </tr>
          </tbody>
        </table>

        <div style={{ marginTop: '50px', textAlign: 'center', color: '#94a3b8', fontSize: '12px' }}>
          <p>CONFIDENTIAL - FOR INTERNAL USE ONLY</p>
          <p>Generated by Yasiru's Security Analyzer</p>
        </div>
      </div>
    </div>
  );
};

export default ExecutiveReport;